### ISSUE TITLE
Expression calculation error

### ISSUE THREAD

**Issue by zhangfz** [apaxa-go/eval#2]
## Interface slices are used as input parameters when different types of parameters are used in the expression. Expression calculation error.

Test code：

package main

import (
	"github.com/apaxa-go/eval"
	"fmt"
)

func main() {
	in := make([]interface{}, 0, 3)
	in = append(in, true)
	in = append(in, 1)
	in = append(in, true)
	expr1, err := eval.ParseString(" (in[1].(int) == 1)  ", "")
	if err != nil {
		return
	}
	expr2, err := eval.ParseString("  in[0].(bool) &&  in[2].(bool)  ", "")
	if err != nil {
		return
	}
	expr3, err := eval.ParseString(" (in[1].(int) == 1) || in[0].(bool) &&  in[2].(bool)  ", "")
	if err != nil {
		return
	}
	a := eval.Args{
		"in": eval.MakeDataRegularInterface(in),
	}
	r1, err := expr1.EvalToInterface(a)
	if err != nil {
		fmt.Println("11111111",err)
		return
	}
	fmt.Printf("%v %T\n", r1, r1)
	r2, err := expr2.EvalToInterface(a)
	if err != nil {
		fmt.Println("2222222",err)
		return
	}
	fmt.Printf("%v %T\n", r2, r1)
	r3, err := expr3.EvalToInterface(a)
	if err != nil {
		fmt.Println("33333333",err)
		return
	}
	fmt.Printf("%v %T\n", r3, r1)

}

Result：

true bool
true bool
**33333333 expression:1:2-1:52: invalid operation: true (type untyped bool) || true (type bool) (invalid types untyped bool and/or bool)**

**Comment by zhangfz** [comment]
## Unrelated to "interface slices ".There is a problem of expression evaluation
Test code：
package main

import (
	"fmt"
	"github.com/apaxa-go/eval"
	"log"
)

func main() {
	src:=" (10 + 20 == 30) || true "
	expr,err:=eval.ParseString(src,"")
	if err!=nil{
		log.Fatal(err)
	}
	r,err:=expr.EvalToInterface(nil)
	if err!=nil{
		log.Fatal(err)
	}
	fmt.Printf("%v %T", r, r)
}

Result：
2017/12/13 09:36:53 expression:1:2-1:22: invalid operation: true (type untyped bool) || true (type untyped constant) (invalid types untyped bool and/or untyped constant)

**Comment by anton-becker** [comment]
Yeh, bug.
Looks like problem in function `binaryOp` in file `data-funcs.go`. In general, I forgot about logical operation with untyped boolean variables at all.
Sorry, but I no longer maintain this lib.

Workaround: convert untyped boolean variable to typed boolean variable:
```
bool(10 + 20 == 30) || true
```
works fine.
PS: untyped boolean variable returns only from comparisons and some language build-in functions.
